@startuml
class ThreadHandler {
  - app_thread: Thread
  - io_thread: Thread
  - announcement_loop
  - udp_thread
  - tcp_thread

  + __init__(app_thread: Thread, io_thread: Thread, announce_handler_loop, tcp_thread, udp_thread): void
  + start_threads(): void
  - _announcement_thread_start(): void
  - _udp_thread_start(): void
  - _tcp_thread_start(): void
}
@enduml