@startuml
class User {
  - addr: str
  - fake_ratio: int = 0
  - test_successes: int = 0
  - test_failures: int = 0
  - index: int = 0

  + add_test(test_res) -> None
}

class Users {
  - torrent_log_and_user_handler

  + __init__(torrent_log_and_user_handler) -> None
  + build_user_dict_from_torrents() -> Dict[User, List[TorrentLog]]
  + return_json(users_dict) -> List[Dict[str, Any]]
}

Users -> User


@enduml